# Generated by Django 5.1.7 on 2025-03-19 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeachCalendarEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('beach', models.CharField(max_length=100)),
                ('walked', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('water_conditions', models.CharField(blank=True, max_length=100, null=True)),
                ('weather_conditions', models.CharField(blank=True, max_length=100, null=True)),
                ('air_temperature', models.SmallIntegerField(blank=True, null=True)),
                ('water_temperature', models.SmallIntegerField(blank=True, null=True)),
                ('swam', models.BooleanField(default=False)),
            ],
        ),
    ]
